name: Context Examples

# event trigger
on: push

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "my step"
        env:
          MY_ACTION: ${{github.action}}
          MY_ACTOR: ${{github.actor}}
        run: |
          echo "Hello! $MY_ACTION"
          echo "Hello! $MY_ACTOR"